### ISSUE TITLE
Add Panda CSS icon

### ISSUE THREAD

**Issue by jacobdalamb** [miguelsolorio/vscode-symbols#155] opened 2023-12-07 17:21 UTC
https://panda-css.com/
file type: `panda.config.{.js, .mjs, .ts}`
icon:
https://panda-css.com/apple-touch-icon.png
https://panda-css.com/favicon.ico
html svg from website:
```
<svg width="124" height="34" viewBox="0 0 124 34" fill="none" xmlns="http://www.w3.org/2000/svg" data-scope="icon"><path d="M41.5908 30.4605H45.784V23.0439H46.0122C46.7254 24.7839 48.4939 25.982 50.8615 25.982C54.5128 25.982 56.9944 23.3006 56.9944 18.052C56.9944 12.7748 54.5128 10.122 50.8615 10.122C48.4939 10.122 46.7254 11.2915 46.0122 13.0601H45.784L45.6414 10.4072H41.5908V30.4605ZM49.2926 22.5875C46.925 22.5875 45.8411 20.7334 45.8411 18.7936V17.3103C45.8411 15.3706 46.925 13.5165 49.2926 13.5165C51.3465 13.5165 52.6871 14.9427 52.6871 18.052C52.6871 21.1612 51.3465 22.5875 49.2926 22.5875Z" fill="currentColor"></path><path d="M63.9711 25.9535C66.3387 25.9535 68.1073 24.7839 68.8204 23.0154H69.0486V25.6968H73.2418V10.4072H69.2197L69.0486 13.0601H68.8204C68.1073 11.2915 66.3387 10.122 63.9711 10.122C60.3199 10.122 57.8667 12.7748 57.8667 18.052C57.8667 23.3006 60.3199 25.9535 63.9711 25.9535ZM65.5685 22.559C63.5147 22.559 62.1455 21.1327 62.1455 18.052C62.1455 14.9427 63.5147 13.5165 65.5685 13.5165C67.9076 13.5165 68.9915 15.3421 68.9915 17.3103V18.7651C68.9915 20.7334 67.9076 22.559 65.5685 22.559Z" fill="currentColor"></path><path d="M75.6896 25.6968H79.8828V17.1962C79.8828 15.2565 81.0809 13.545 83.2488 13.545C85.2741 13.545 86.1299 14.8001 86.1299 17.3674V25.6968H90.3231V16.4546C90.3231 11.862 87.984 10.122 84.9318 10.122C82.7639 10.122 80.8812 11.1489 80.054 13.1742H79.8828L79.7117 10.4072H75.6896V25.6968Z" fill="currentColor"></path><path d="M97.8192 25.9535C100.187 25.9535 101.955 24.7839 102.668 23.0154H102.897L103.039 25.6968H107.09V4.90186H102.897V13.0601H102.668C101.955 11.2915 100.187 10.122 97.8192 10.122C94.168 10.122 91.7148 12.7748 91.7148 18.052C91.7148 23.3006 94.168 25.9535 97.8192 25.9535ZM99.4166 22.559C97.3628 22.559 95.9936 21.1327 95.9936 18.052C95.9936 14.9427 97.3628 13.5165 99.4166 13.5165C101.756 13.5165 102.84 15.3421 102.84 17.3103V18.7651C102.84 20.7334 101.756 22.559 99.4166 22.559Z" fill="currentColor"></path><path d="M114.729 25.9535C117.097 25.9535 118.865 24.7839 119.579 23.0154H119.807V25.6968H124V10.4072H119.978L119.807 13.0601H119.579C118.865 11.2915 117.097 10.122 114.729 10.122C111.078 10.122 108.625 12.7748 108.625 18.052C108.625 23.3006 111.078 25.9535 114.729 25.9535ZM116.327 22.559C114.273 22.559 112.904 21.1327 112.904 18.052C112.904 14.9427 114.273 13.5165 116.327 13.5165C118.666 13.5165 119.75 15.3421 119.75 17.3103V18.7651C119.75 20.7334 118.666 22.559 116.327 22.559Z" fill="currentColor"></path><path d="M0 4.12886C0 2.01551 1.71321 0.302307 3.82656 0.302307H29.221C31.3343 0.302307 33.0475 2.01551 33.0475 4.12886V29.8711C33.0475 31.9845 31.3343 33.6977 29.221 33.6977H3.82656C1.71321 33.6977 0 31.9845 0 29.8711V4.12886Z" fill="#F6E458"></path><path d="M21.1783 7.76704C19.355 7.24329 17.4952 7.17211 15.6 7.34161C14.5394 7.45181 13.5198 7.66234 12.5363 8.03177C10.4105 8.83028 8.81442 10.2132 7.86268 12.2955C7.18036 13.7883 6.93376 15.374 6.90806 17.0011C6.8809 18.7205 7.09638 20.4162 7.43877 22.0974C7.74912 23.6212 8.16242 25.1152 8.75268 26.5574C8.80876 26.6944 8.87861 26.7406 9.02829 26.7403C10.8951 26.7363 12.762 26.7363 14.6289 26.7363C15.1815 26.7363 15.7342 26.7363 16.2869 26.7362C16.3292 26.7362 16.3715 26.7339 16.4202 26.7312C16.445 26.7299 16.4715 26.7284 16.5005 26.7271C16.4893 26.7004 16.4793 26.6759 16.4698 26.6529C16.4514 26.6077 16.4353 26.5684 16.4173 26.5299C16.2823 26.2411 16.1445 25.9536 16.0067 25.666C15.7078 25.0422 15.409 24.4184 15.1387 23.7824C14.3188 21.8537 13.691 19.8678 13.4994 17.7657C13.4149 16.8382 13.4266 15.916 13.684 15.0122C13.9781 13.9791 14.6093 13.2498 15.6558 12.9449C16.6168 12.665 17.5912 12.6668 18.5469 12.9759C19.3999 13.2517 19.956 13.8344 20.1926 14.7068C20.3743 15.3768 20.3742 16.054 20.2368 16.7295C20.1309 17.2495 19.9179 17.7241 19.5344 18.1037C18.8464 18.7847 17.9873 18.9413 17.0654 18.8891C16.9014 18.8798 16.7379 18.8619 16.5694 18.8433C16.4905 18.8347 16.4105 18.8259 16.3288 18.8178C16.3311 18.8439 16.3324 18.8679 16.3337 18.8904C16.336 18.9347 16.3381 18.9731 16.3472 19.0098C16.3865 19.1677 16.424 19.3262 16.4614 19.4847C16.5516 19.8665 16.6418 20.2483 16.7577 20.6221C16.9855 21.3561 17.2502 22.0725 17.5504 22.7719C19.6902 22.6049 21.661 22.073 23.7528 20.8173C23.7842 20.7975 23.8128 20.7796 23.8414 20.7618C24.7399 20.2024 25.4671 19.4768 25.9686 18.5398C26.7808 17.0224 26.9391 15.3997 26.6978 13.7248C26.4488 11.9962 25.6731 10.5453 24.3377 9.40723C23.4116 8.61786 22.3406 8.10091 21.1783 7.76704Z" fill="black"></path></svg>
```

**Comment by miguelsolorio** [comment] 2024-01-03 19:35
Duplicate of https://github.com/miguelsolorio/vscode-symbols/issues/144

**Closed by miguelsolorio** 2024-01-03 19:35 UTC
Labels: icon request
